apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::134330686145:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-13LIE1L9SN7QG
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::134330686145:role/UdacityFlaskDeployCBKubectlRole
      username: build  
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-04T10:33:51Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1351"
  uid: 08c1296a-4f61-44b8-8ea3-ef825ce8c113
